### ISSUE TITLE
Custom Space User Management Plugin incompatible for CONF 5.10

### ISSUE THREAD

**Issue by baaderst** [sillycat/confluence-space-user-management#31]
Hello,
we recently updated to CONF 5.10.4 and unfortunately one of the most useful plugins - Custom Space User Management Plugin - is marked as incompatible. But as far as I recognized the plugin seems to work properly. I have it still running on our QA system. Since it is against security policies to run incompatible or outdated plugins on production I would like to ask you for an official update of that plugin. 

Many thanks
Stefan

**Comment by miburi** [comment]
I spoke with the developers of the plugin since we upgraded to Confluence 6.0.2 and the plugin is now broken but they're going to be releasing a paid version with support and will be updating the plugin. Hopefully it won't be too much longer, but this is a widely used plugin by many that don't want to grant Confluence Administrator permissions for users that just need to manage Groups.

**Comment by javahollic** [comment]
Version 2.5.0 has now been submitted to Marketplace for approval, watch the addon for release notification.

All future work done will be through https://thepluginpeople.atlassian.net/projects/CSUM
